source 'https://github.com/CocoaPods/Specs.git'

platform:ios, '7.0'

pod 'Reachability'
pod 'MBProgressHUD', '~> 0.8'
pod 'uservoice-iphone-sdk', '~> 3.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'RJImageLoader'
pod 'SDWebImage'
pod 'Parse', '~> 1.7.2'
pod 'ParseUI', '~> 1.1.3'
pod 'ParseCrashReporting', '~> 1.7'
pod 'ParseFacebookUtilsV4', '~> 1.7'
pod 'FMDB', '~> 2.5'
pod 'ActionSheetPicker-3.0'
pod 'IQDropDownTextField'
pod 'IQKeyboardManager'

pod 'RBStoryboardLink', '~> 0.1'
pod 'ECSlidingViewController', '~> 2.0'