source 'https://github.com/CocoaPods/Specs.git'

platform:ios, '7.0'

pod 'Reachability'
pod 'MBProgressHUD', '~> 0.8'
pod 'uservoice-iphone-sdk', '~> 3.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'RJImageLoader'
pod 'SDWebImage'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Parse', '~> 1.7.2'
pod 'ParseUI', '~> 1.1.3'